module.exports = {
  apps: [
    {
      name: "gateway",
      script: "./index.js",
      cwd: "./gateway",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 2000 }
    },
    {
      name: "auth",
      script: "./index.js",
      cwd: "./services/auth",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3001 },
    },
    {
      name: "user",
      script: "./index.js",
      cwd: "./services/user",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3002 },
    },
    {
      name: "analytics-dashboard",
      script: "./index.js",
      cwd: "./services/analytics-dashboard-new",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3003 },
    },
    {
      name: "assets",
      script: "./index.js",
      cwd: "./services/assets",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3004 },
    },
    {
      name: "billing-subscription",
      script: "./index.js",
      cwd: "./services/billing-subscription",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3005 },
    },
    {
      name: "category",
      script: "./index.js",
      cwd: "./services/category",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3006 },
    },
    {
      name: "notification",
      script: "./index.js",
      cwd: "./services/notification",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3007 },
    },
    {
      name: "template",
      script: "./index.js",
      cwd: "./services/template",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3008 },
    },
    {
      name: "ticket-support",
      script: "./index.js",
      cwd: "./services/ticket-support",
      namespace: "story-maker-admin",
      watch: false,
      exec_mode: "fork",
      env: { NODE_ENV: "development", PORT: 3009 },
    }
  ]
};
